name: Python CI on Windows

on: [push, pull_request]

jobs:
  quality-check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.5'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest==8.0.1 pytest-cov pandas scikit-learn==1.2.1 matplotlib pylint joblib==1.2.0 flask

    - name: Code Style Check (PEP 8)
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Static Analysis
      run: |
        pylint **/*.py --disable=E0401
