name: Unit Testing

on:
  pull_request:
    branches:
      - test

jobs:
  unit-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install pytest==8.0.1 pytest-cov pandas scikit-learn==1.2.1 matplotlib pylint joblib==1.2.0

      - name: Run unit tests
        run: |
          python -m pytest test_models.py
